const express = require('express');
const router = express.Router();
const User = require('../models/User');
const snarkjs = require('snarkjs');
const fs = require('fs');
const path = require('path');

// Path to the verification key (generated by setup_zkp.sh)
const vKeyPath = path.join(__dirname, '../../config/verification_key.json');

// @route   POST api/auth/register
// @desc    Register a new user with ZKP public signals
router.post('/register', async (req, res) => {
  const { username, publicSignals } = req.body;

  try {
    let user = await User.findOne({ username });
    if (user) {
      return res.status(400).json({ msg: 'User already exists' });
    }

    user = new User({
      username,
      publicSignals,
    });

    await user.save();
    res.status(201).json({ msg: 'User registered successfully' });
  } catch (err) {
    console.error(err.message);
    res.status(500).send('Server error');
  }
});

// @route   POST api/auth/login
// @desc    Login user by verifying ZKP proof
router.post('/login', async (req, res) => {
  const { username, proof, publicSignals } = req.body;

  try {
    const user = await User.findOne({ username });
    if (!user) {
      return res.status(400).json({ msg: 'Invalid credentials' });
    }

    // 1. Verify that the public signals provided match the ones in the DB
    const signalsMatch = publicSignals.length === user.publicSignals.length &&
                         publicSignals.every((val, i) => val.toString() === user.publicSignals[i].toString());

    if (!signalsMatch) {
        console.log('Signal mismatch details:', { sent: publicSignals, stored: user.publicSignals });
        return res.status(401).json({ msg: 'Public signal mismatch' });
    }

    // 2. Verify the proof
    if (!fs.existsSync(vKeyPath)) {
        console.warn('Verification key not found. Skipping real verification for dev.');
        // For development before circuit is compiled:
        return res.json({ msg: 'Logged in (DEV MODE: No vKey found)', userId: user._id });
    }

    const vKey = JSON.parse(fs.readFileSync(vKeyPath));
    const res_verify = await snarkjs.groth16.verify(vKey, publicSignals, proof);

    if (res_verify) {
        res.json({ msg: 'Login successful', userId: user._id });
    } else {
        res.status(401).json({ msg: 'Invalid ZK proof' });
    }

  } catch (err) {
    console.error('ZKP Verification Error:', err);
    res.status(500).send('Verification failed');
  }
});

module.exports = router;
